---
title: "Tessellation"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(Kaashi)
```

```{r tiling_30_0.5}
tile <- pattern(theta = 30, delta = 0.5, polyLine = F)
tiling <- tessellation(tile, n = 5)
tilePlotter(tiling,tileColor = c("#FFAD00","#FFAD00","#BF5700","#002D7B","#007EA1"),
            borderSize = 0.1)
```

```{r hexagonal_tile}
# Hexagonal Box
s3 = sqrt(3)
hexagonal = rbind(c(-1,0), c(1,0), c(2,s3), c(1,2*s3), c(-1,2*s3),c(-2,s3),c(-1,0))
tile <- pattern(theta = 45, n = 6, delta = 0.2, start_points = c(0,0),
                box = hexagonal, drawBox = T, polyLine = T)
tilePlotter(tile)
```

```{r hexagonal_tiling}
tile <- pattern(theta = 60, n = 6, delta = 0.2, 
                start_points = c(0,0), box = hexagonal, dist = 0.05, polyLine = F)
tiling <- tessellation(tile,n = 2, type = "6-3", box = hexagonal)

tilePlotter(tiling,tileColor = c("#FFAD00","#FFAD00","#007EA1","#002D7B"),
            borderSize = 0.1)
```

```{r riangle_tile}
box = rbind(c(-1,0), c(1,0), c(0,sqrt(3)),c(-1,0))
tile <- pattern(25,0.5,n = 3, start_points = c(0,0),box = box, polyLine = T,drawBox = T)
tilePlotter(tile)
```

```{r triangle_tiling}
tile <- pattern(25,0.5,n = 3, start_points = c(0,0),box = box, polyLine = F,dist = 0.01)
tiling <- tessellation(tile, n = 2,box = box,type = "3-6")
tilePlotter(tiling,tileColor = c("#FFAD00","#FFAD00","#FFAD00","#007EA1","#002D7B"),
            borderSize = 0.001)
```

